---
- name: Update dns - workaround for OVH hosts
  lineinfile: dest=/etc/resolv.conf regexp='^nameserver 127\.0\.0\.1' line='nameserver 127.0.0.1'
- lineinfile: dest=/etc/resolv.conf regexp='^nameserver 8\.8\.8\.8' line='nameserver 8.8.8.8'
  
- name: Install docker
  action: apt pkg=docker.io state=installed
  notify: Restart Docker

- name: install docker-py
  pip: name=docker-py version=0.3.1

